### ISSUE TITLE
Option to open downloads tab with a single click

### ISSUE THREAD

**Issue by anewuser** [Niamor/tabdownloads#1]
Please consider adding an option to open the tab with a single click on the download button and skip the popup/floating panel altogether.

**Comment by Niamor** [comment]
I'd really like to add that as an option but I'm not really sure where to start.
It looks like making another button would be the easiest option, I think other addons do that already and the reason I didn't is because I wanted to keep the original behavior and icon style of Firefox.
I'll try to look at it a bit more and if you have any ideas as to where I should look please tell me.
Thank you for your suggestion.

**Comment by anewuser** [comment]
This extension can do that: https://addons.mozilla.org/firefox/addon/download-manager-tweak/ . I stopped using it because each Firefox update has been breaking its features one by one since the implementation of Australis, but I guess that it can still open the download manager in a new tab from the default button, if you check the appropriate setting.
